### PR TITLE
Add example configs

### PR DESCRIPTION
**Pull request by nemchik**
for Jackett, Monitorr, NZBGet, NZB Hydra, Organizr, Portainer, and Transmission

[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

### CODE REVIEW

**Comment by aptalca** [comment]
Jenkins test this please

**Comment by CHBMB** [comment]
If I'm being really critical the auth lines are slightly out of line!

**Comment by nemchik** [comment]
@CHBMB as they are in the existing samples https://github.com/linuxserver/docker-letsencrypt-armhf/blob/master/root/defaults/proxy-confs/emby.subdomain.conf.sample but I'd be more than happy to fix those :D

**Comment by aptalca** [comment]
That's fine, they are just commented out

**Comment by CHBMB** [comment]
@nemchik That's sloppy work on @aptalca's part..... :laughing:

**Comment by aptalca** [comment]
Heyy, when you uncomment them, they fall in line
(•_•) ( •_•)>⌐□-□ (⌐□_□)

**Pull request merged**
